// h5-subapp-setup/assets/react-template/src/Home.jsx
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';

export default function Home() {
  const [info, setInfo] = useState(null);
  const [dark, setDark] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    let alive = true;
    // 直接使用基座 Bridge 中间件 window.RN
    Promise.all([window.RN.APP.GETINFO(), window.RN.SYSTEM.GETDARKMODE()])
      .then(([appInfo, darkMode]) => {
        if (!alive) return;
        setInfo(appInfo);
        setDark(darkMode.mode);
      })
      .catch((e) => alive && setError(e && e.code ? `${e.code}: ${e.message}` : String(e)));
    return () => {
      alive = false;
    };
  }, []);

  return (
    <div>
      <h1>H5 子应用 (React)</h1>
      <nav>
        <Link to="/">首页</Link> | <Link to="/about">关于</Link>
      </nav>
      <h2>首页</h2>
      {info && <p>App: {info.appVersion} / Bridge: {info.bridgeVersion} / {info.platform}</p>}
      {dark && <p>深色模式: <b>{dark}</b></p>}
      {error && <p style={{ color: '#b00020' }}>Bridge 调用失败: {error}</p>}
    </div>
  );
}

// h5-subapp-setup/assets/vue-template/src/views/Home.vue
<script setup>
import { onMounted, ref } from 'vue';

const info = ref(null);
const dark = ref(null);
const error = ref(null);

onMounted(async () => {
  try {
    // 直接使用基座 Bridge 中间件 window.RN
    const [appInfo, darkMode] = await Promise.all([
      window.RN.APP.GETINFO(),
      window.RN.SYSTEM.GETDARKMODE(),
    ]);
    info.value = appInfo;
    dark.value = darkMode.mode;
  } catch (e) {
    error.value = e && e.code ? `${e.code}: ${e.message}` : String(e);
  }
});
</script>

<template>
  <div>
    <h2>首页</h2>
    <p v-if="info">App: {{ info.appVersion }} / Bridge: {{ info.bridgeVersion }} / {{ info.platform }}</p>
    <p v-if="dark">深色模式: <b>{{ dark }}</b></p>
    <p v-if="error" style="color: #b00020">Bridge 调用失败: {{ error }}</p>
  </div>
</template>
